name: update

on:
    workflow_dispatch:
    schedule:
        - cron: "10 7 * * *" # At 7:10 UTC

jobs:
    generate_list:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo content
              uses: actions/checkout@v4
              with:
                  submodules: true
                  fetch-depth: 0

            - name: Update rstthreats
              run: |
                  git submodule update --remote --merge

            - name: setup python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: execute py script
              run: |
                  python extract.py

            - name: commit files
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add -A
                  git diff --name-only --cached --exit-code || ( git commit -am "update lists" && git push )
